# Thread 1
NestedLoopWithExceptionRepresentationTest.operation() at :0
  escape = "START" at NestedLoopWithExceptionRepresentationTest.kt:41
  nestedLoopWithException(): threw RuntimeException at NestedLoopWithExceptionRepresentationTest.kt:43
    escape = "METHOD_START" at NestedLoopWithExceptionRepresentationTest.kt:26
    i = 1 at NestedLoopWithExceptionRepresentationTest.kt:27
    loop(2 iterations) at NestedLoopWithExceptionRepresentationTest.kt:27
      <iteration 1> at NestedLoopWithExceptionRepresentationTest.kt:27
        a = 1 at NestedLoopWithExceptionRepresentationTest.kt:28
        j = 1 at NestedLoopWithExceptionRepresentationTest.kt:29
        loop(3 iterations) at NestedLoopWithExceptionRepresentationTest.kt:29
          <iteration 1> at NestedLoopWithExceptionRepresentationTest.kt:29
            escape = "1.1" at NestedLoopWithExceptionRepresentationTest.kt:30
            j = 2 at NestedLoopWithExceptionRepresentationTest.kt:29
          <iteration 2> at NestedLoopWithExceptionRepresentationTest.kt:29
            escape = "1.2" at NestedLoopWithExceptionRepresentationTest.kt:30
            j = 3 at NestedLoopWithExceptionRepresentationTest.kt:29
          <iteration 3> at NestedLoopWithExceptionRepresentationTest.kt:29
            escape = "1.3" at NestedLoopWithExceptionRepresentationTest.kt:30
            j = 4 at NestedLoopWithExceptionRepresentationTest.kt:29
        i = 2 at NestedLoopWithExceptionRepresentationTest.kt:27
      <iteration 2> at NestedLoopWithExceptionRepresentationTest.kt:27
        a = 2 at NestedLoopWithExceptionRepresentationTest.kt:28
        j = 1 at NestedLoopWithExceptionRepresentationTest.kt:29
        loop(2 iterations) at NestedLoopWithExceptionRepresentationTest.kt:29
          <iteration 1> at NestedLoopWithExceptionRepresentationTest.kt:29
            escape = "2.1" at NestedLoopWithExceptionRepresentationTest.kt:30
            j = 2 at NestedLoopWithExceptionRepresentationTest.kt:29
          <iteration 2> at NestedLoopWithExceptionRepresentationTest.kt:29
            escape = "2.2" at NestedLoopWithExceptionRepresentationTest.kt:30
  e = RuntimeException@1 at NestedLoopWithExceptionRepresentationTest.kt:44
  escape = "CAUGHT EXCEPTION" at NestedLoopWithExceptionRepresentationTest.kt:45
  escape = "END" at NestedLoopWithExceptionRepresentationTest.kt:47
