= Validation function validateWithError has failed =
| -------------------------------------------------------------- |
|                  Thread 1                  |     Thread 2      |
| -------------------------------------------------------------- |
| operation(): void                          |                   |
| -------------------------------------------------------------- |
| operation(): void                          | operation(): void |
| -------------------------------------------------------------- |
| operation(): void                          |                   |
| -------------------------------------------------------------- |
| validateWithError(): IllegalStateException |                   |
| -------------------------------------------------------------- |

---
All operations above the horizontal line | ----- | happen before those below the line
---


java.lang.IllegalStateException: Validation works!
	at org.jetbrains.kotlinx.lincheck_test.representation.ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:42)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution1519.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:172)
	at java.base/java.lang.Thread.run(Thread.java:840)


The following interleaving leads to the error:
| ----------------------------------------------------------- |
|                   Thread 1                    |  Thread 2   |
| ----------------------------------------------------------- |
| operation()                                   |             |
| ----------------------------------------------------------- |
|                                               | operation() |
| operation()                                   |             |
| ----------------------------------------------------------- |
| operation()                                   |             |
| ----------------------------------------------------------- |
| validateWithError(): IllegalStateException #1 |             |
| ----------------------------------------------------------- |

Detailed trace:
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                               Thread 1                                                               |                                           Thread 2                                           |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| operation()                                                                                                                          |                                                                                              |
|   validateInvoked ➜ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:34)                                         |                                                                                              |
|   result: void                                                                                                                       |                                                                                              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                                                                                                      | operation()                                                                                  |
|                                                                                                                                      |   validateInvoked ➜ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:34) |
|                                                                                                                                      |   result: void                                                                               |
| operation()                                                                                                                          |                                                                                              |
|   validateInvoked ➜ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:34)                                         |                                                                                              |
|   result: void                                                                                                                       |                                                                                              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| operation()                                                                                                                          |                                                                                              |
|   validateInvoked ➜ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:34)                                         |                                                                                              |
|   result: void                                                                                                                       |                                                                                              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| validateWithError(): IllegalStateException #1                                                                                        |                                                                                              |
|   validateInvoked ➜ 0 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:41)                                 |                                                                                              |
|   validateInvoked = 1 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:41)                                 |                                                                                              |
|   validateInvoked ➜ 1 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:42)                                 |                                                                                              |
|   "Validation works!".toString(): "Validation works!" at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:42) |                                                                                              |
|   result: IllegalStateException #1                                                                                                   |                                                                                              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
